
[functions.payments]
enabled = true
verify_jwt = true
import_map = "./functions/payments/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/payments/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/payments/*.html" ]

[functions.categories]
enabled = true
verify_jwt = true
import_map = "./functions/categories/deno.json"
# Uncomment to specify a custom file path to the entrypoint.
# Supported file extensions are: .ts, .js, .mjs, .jsx, .tsx
entrypoint = "./functions/categories/index.ts"
# Specifies static files to be bundled with the function. Supports glob patterns.
# For example, if you want to serve static HTML pages in your function:
# static_files = [ "./functions/categories/*.html" ]

[auth]
site_url = "env(AUTH_SITE_URL)"
additional_redirect_urls = [
	"env(AUTH_REDIRECT_URL)",
]

[auth.external.google]
enabled = true
client_id = "env(SUPABASE_GOOGLE_CLIENT_ID)"
secret = "env(SUPABASE_GOOGLE_CLIENT_SECRET)"
redirect_uri = "env(SUPABASE_GOOGLE_REDIRECT_URL)"
