name: Backend CI

on:
  pull_request:
    paths:
      - ".github/workflows/backend_ci.yaml"
      - "apps/api/supabase/**"
      - "!**/docs/**"

jobs:
  check:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/api/supabase/functions/${{ matrix.edge-function }}
    strategy:
      matrix:
        edge-function: ["categories"] # "payments" は未対応のため除外
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6

      - name: Setup Deno
        uses: denoland/setup-deno@e95548e56dfa95d4e1a28d6f422fafe75c4c26fb # v2.0.3
        with:
          deno-version: v2.x

      - name: Check
        run: deno check --config deno.json **/*.ts

      - name: Format
        run: deno fmt --check

      - name: Lint
        run: deno lint

      - name: Test
        run: deno test --allow-all
