name: Backend CI

on:
  pull_request:
    paths:
      - "!**/docs/**"
      - ".github/workflows/backend_ci.yaml"
      - "apps/api/supabase/**"

jobs:
  check:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: apps/api/supabase/functions/${{ matrix.edge-function }}
    strategy:
      matrix:
        edge-function: ["categories", "payments"]
    steps:
      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5

      - name: Setup Deno
        uses: denoland/setup-deno@2f7698fd116bfedbd1c3cd4119337b5a787ef53a # v2
        with:
          deno-version: v2.x

      - name: Check
        run: deno check --config deno.json **/*.ts

      - name: Format
        run: deno fmt --check

      - name: Lint
        run: deno lint

      - name: Test
        run: deno test --allow-all
