name: Scripts CI

on:
  pull_request:
    paths:
      - "!**/docs/**"
      - ".github/workflows/scripts_ci.yaml"
      - "scripts/**"

jobs:
  import_to_firestore_ci:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: scripts/import_to_firestore
    steps:
      - uses: actions/checkout@8e8c483db84b4bee98b60c0593521ed34d9990e8 # v6

      - name: Setup Deno
        uses: denoland/setup-deno@e95548e56dfa95d4e1a28d6f422fafe75c4c26fb # v2
        with:
          deno-version: v2.x

      - name: Check
        run: deno check

      - name: Format
        run: deno fmt --check

      - name: Lint
        run: deno lint

      - name: Test
        run: deno test --allow-read
